development:
  dialect: postgres
  database: crypton_development
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/crypton_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/crypton_production?sslmode=disable"}}
